### ISSUE TITLE
Call to undefined function Mindee\Input\str_starts_with()

### ISSUE THREAD

**Issue by shajeerEmiratesZone** [mindee/mindee-api-php#46]
### Prerequisites

Put an X between the brackets on this line if you have done all of the following:

* [X] Reproduced the problem or exposed a new need
* [x] Checked the GitHub existing issues

### Description

Im getting an error **Fatal error: Uncaught Error: Call to undefined function Mindee\Input\str_starts_with()** in vendor\mindee\mindee\src\Input\URLInputSource.php:23 when using $inputSource = $mindeeClient->sourceFromUrl('fileurl');

### Steps to Reproduce

1. Initialise Mindee Client $mindeeClient = new Client("API_KEY");
2. Load from URL $inputSource = $mindeeClient->sourceFromUrl('fileurl');

**Expected behavior:**
Should provide API response data.

**Actual behavior:**

**Fatal error: Uncaught Error: Call to undefined function Mindee\Input\str_starts_with()** in vendor\mindee\mindee\src\Input\URLInputSource.php:23
Stack trace: #0 \vendor\mindee\mindee\src\Client.php(112): Mindee\Input\URLInputSource->__construct('https://s3.me-c...') #1 index.php(15): Mindee\Client->sourceFromUrl('https://s3.me-c...') #2 {main} thrown in vendor\mindee\mindee\src\Input\URLInputSource.php on line 23

**Reproduces how often:**

100% of the time
### Versions
"mindee/mindee": "^1.3"
php : 7.4.33

### Additional Information
The package says it works on PHP version 7.4 and above but I think it uses php 8+ functions/methods.

**Comment by sebastianMindee** [comment]
Thank you for raising this, fixed in #47.

Fair warning, though: it seems like issues like this one can't be reliably tested currently, because they go through the CI without any issues. I assume that the PHP install action comes bundled with functions from PHP > 8.0, and, somehow, the 7.4 installation manages to get access to it...

Anyway, don't hesitate to ping me personally if you see instances of undefined functions.

**Comment by shajeerEmiratesZone** [comment]
Hello. Thabks for the quick update, but the issue still seems to be present in the updated version, but with a new error message. Please find below the error message Im facing now, while using sourceFromUrl():

Fatal error: Uncaught Mindee\Error\MindeeApiException: Cannot edit non-local input sources. in vendor\mindee\mindee\src\Client.php:288 Stack trace: #0 vendor\mindee\mindee\src\Client.php(326): Mindee\Client->makeParseRequest('Mindee\\Product\\...', Object(Mindee\Input\URLInputSource), Object(Mindee\Input\PredictMethodOptions)) #1 C:\xampp\htdocs\shajeer\mindee_passport_api\index.php(19): Mindee\Client->parse('Mindee\\Product\\...', Object(Mindee\Input\URLInputSource)) #2 {main} thrown in vendor\mindee\mindee\src\Client.php on line 288

**Comment by sebastianMindee** [comment]
Thank you for the additional feedback, fixed in #50 

Many functions relying on a future implementation of PDF handling are visibly not tested well. I've added a couple more tests, but we will most likely implement something a bit more thorough in the future when the PDF operations are added to the library.

**Comment by shajeerEmiratesZone** [comment]
**Fatal error: Uncaught Error: Object of class Mindee\Input\URLInputSource could not be converted to string in vendor\mindee\mindee\src\Http\Endpoint.php:129 Stack trace: #0 vendor\mindee\mindee\src\Http\Endpoint.php(129): curl_setopt(Resource id #22, 10015, Array) #1 vendor\mindee\mindee\src\Http\Endpoint.php(170): Mindee\Http\Endpoint->initCurlSessionPost(Object(Mindee\Input\URLInputSource), false, false, false, false) #2 vendor\mindee\mindee\src\Client.php(298): Mindee\Http\Endpoint->predictRequestPost(Object(Mindee\Input\URLInputSource), false, false, false) #3 vendor\mindee\mindee\src\Client.php(330): Mindee\Client->makeParseRequest('Mindee\\Product\\...', Object(Mindee\Input\URLInputSource), Object(Mindee\Input\PredictMethodOptions)) #4 index.php(19): Mindee\ in vendor\mindee\mindee\src\Http\Endpoint.php on line 129**

**Comment by sebastianMindee** [comment]
Thank you for that as well, and my apologies for the needless back & forth... Fixed in #52.

I implemented a more in-depth test & fully tested the feature from end-to-end this time, so URL enqueuing shouldn't cause any more issues. I blame Monday as the reason why I didn't do it from the beginning.
